#!/bin/bash

NET=$1
NUM=$2
ROOT=$(git rev-parse --show-toplevel)
DEST=$ROOT/tmp

$ROOT/bin/bnc $ROOT/data/net/$NET.net -w circuit=$DEST/$NET.ac -o collapse=0
for ((i=1; i <= $NUM; i++)); do
    cp $ROOT/data/net/$NET.net $DEST/$NET.$i.net
    $ROOT/bin/bnc $DEST/$NET.$i.net -o collapse=0 -r part=$DEST/$NET.$i.part -w circuit=$DEST/$NET.$i.ac
done
