#!/bin/bash

NET=$1
SUBSETSIZE=$2
VARIABLES=(${@:3})
NRVARIABLES=${#VARIABLES[@]}
ROOT=$(git rev-parse --show-toplevel)
DEST=$ROOT/tmp

VARS=$SUBSETSIZE
if [[ $VARS -eq 2 ]]; then
    FILENUM=0
    for ((i=0; i < $NRVARIABLES; i++)); do
        for ((j=$i+1; j < $NRVARIABLES; j++)); do
            FILENUM=$(($FILENUM + 1))
            FILENAME="$NET.${FILENUM}.part"
            echo "partition 2" > $DEST/$FILENAME
            echo "${VARIABLES[$i]},${VARIABLES[$j]}::" >> $DEST/$FILENAME

            COMMA=0
            for ((k=0; k < $NRVARIABLES; k++)); do
                if [[ $k -ne $i ]] && [[ $k -ne $j ]]; then
                    [ $COMMA -eq 1 ] && echo -n "," >> $DEST/$FILENAME
                    echo -n "${VARIABLES[$k]}" >> $DEST/$FILENAME
                    COMMA=1
                fi
            done
            echo "::" >> $DEST/$FILENAME
            echo "$DEST/$FILENAME"
        done
    done
elif [[ $VARS -eq 1 ]]; then
    FILENUM=0
    for ((i=0;i < $NRVARIABLES; i++)); do
        FILENUM=$(($FILENUM + 1))
        FILENAME="$NET.${FILENUM}.part"
        echo "partition 2" > $DEST/$FILENAME
        echo "${VARIABLES[$i]}::" >> $DEST/$FILENAME

        COMMA=0
        for ((k=0; k < $NRVARIABLES; k++)); do
            if [[ $k -ne $i ]]; then
                [ $COMMA -eq 1 ] && echo -n "," >> $DEST/$FILENAME
                echo -n "${VARIABLES[$k]}" >> $DEST/$FILENAME
                COMMA=1
            fi
        done
        echo "::" >> $DEST/$FILENAME
        echo "$FILENAME"
    done
fi

echo "in $DEST"

