#!/bin/bash

trap '
  trap - INT # restore default INT handler
  kill -s INT "$$"
' INT


read -p 'NET name    : ' NET

ROOT=$(git rev-parse --show-toplevel)
NUM="$ROOT/data/num/$NET.num"
if [ ! -f "$NUM" ]; then
    echo "file '$NUM' not found"
    exit
fi
VARIABLES=($(cat $ROOT/data/num/$NET.num))
echo -e "\n  ${#VARIABLES[@]} variables: ${VARIABLES[@]}\n"

read -p '#Partitions : ' PARTITIONS
read -p 'Par. sizes  : ' K


DEST=$ROOT/tmp
mkdir -p $DEST

cp $ROOT/data/net/$NET.net $DEST
if [ ! $? ]; then
    echo "no $ROOT/data/net/$NET.net"
    exit
fi

echo "========================================================="
./gen-part-py $NET $PARTITIONS $K $SUBSETSIZE ${VARIABLES[@]}
echo "========================================================="

echo "How many partitions files were generated?"
while [ 1 ]; do
    read NUM
    if ! [[ "$NUM" =~ ^[0-9]+$ ]]; then
        echo "Sorry, integers only"
    else
        break
    fi
done

./gen-circuits $NET $NUM
./gen-bnmc-input $NET $NUM
./run-circuits $NUM

