#!/bin/bash

if ! [ $# -ge 1 ]; then
    echo "Usage: $(basename "$1") <NET> [ARGS]" 1>&2
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/environment $1

ARGS=""
[ -f "$NUM" ] && [[  "${@:2}" != *'w elim'* ]] && ARGS="-r elim=$NUM"

if [[ "${@:2}" == *"sdd"* ]]; then
    OUTFILE="$SDD_OUTFILE"
elif [[ "${@:2}" == *"obdd"* ]]; then
    OUTFILE="$OBDD_OUTFILE"
elif [[ "${@:2}" == *"part="* ]] && [[ "${@:2}" == *"circuit="* ]]; then
    OUTFILE="$PART_CIRCUIT_OUTFILE"
elif [[ "${@:2}" == *"part="* ]] && [[ "${@:2}" != *"circuit="* ]]; then
    OUTFILE="$PART_OUTFILE"
elif [[ "${@:2}" != *"part="* ]] && [[ "${@:2}" == *"circuit="* ]]; then
    OUTFILE="$CIRCUIT_OUTFILE"
else
    OUTFILE="$DEFAULT_OUTFILE"
fi

CMD="$BNC ${HUGIN} $ARGS ${@:2}"
echo "== $CMD =="
echo "output: $OUTFILE"

limit_time 3600 stdbuf -o 0 $CMD -o resources=0.8  2>&1 | tee $OUTFILE
