#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: compare_inference <NET> [args]" 1>&2
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/environment $1

if [ ! -f $PARTCIRCUIT ]; then
    echo "Create partitioned WPBDD circuit first. ($PARTCIRCUIT not found)." 1>&2
    exit 1
fi

if [ ! -f $CIRCUIT ]; then
    echo "Create WPBDD circuit first. ($CIRCUIT not found)." 1>&2
    exit 1
fi

echo "\
load net $HUGIN
load map $MAP
load pwpbdd $PARTCIRCUIT $PART $([ -f $COMP ] && echo $COMP)
load wpbdd $CIRCUIT
compare
" > $INFERENCEINPUT

echo "Running inference..."
limit_time 3600 $INFERENCE ${@:2} < $INFERENCEINPUT
echo "Inference done."

