#!/bin/bash

if ! [ $# -ge 1 ]; then
    echo "Usage: create_wpbdd_circuit <NET> [ARGS]" 1>&2
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/environment $1

$COMPILER $NET -w circuit=${CIRCUIT} -o collapse=0 ${@:2}

