#!/bin/bash

if ! [ $# -ge 1 ]; then
    echo "Usage: create_wpbdd_circuit <NET> [ARGS]" 1>&2
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/environment $1

ARGS=""
[ -f "$NUM" ] && ARGS="-r elim=$NUM"

while [ ! -f "$PART" ]; do
    read -p "Partitioning not found. Create one (Y/n)? " -n 1 -r INPUT 2>&1; echo
    case "$INPUT" in
        y|Y|'' ) $DIR/create_partitioning $NET; break ;;
        n|N )    break;;
    esac
done

[ -f "$PART" ] && ARGS="$ARGS -r part=$PART"

$COMPILER $NET $ARGS -w circuit=${CIRCUIT} -o collapse=0 ${@:2}

