#!/bin/bash

FILE=$1
NAME=${FILE%.*}
EXTENSION=${FILE##*.}

if [ "$EXTENSION" == "dot" ]; then
    dot -Tps $FILE -o ${NAME}.ps
    if [ $# -gt 1 ]; then
        evince "${NAME}.ps" 2>/dev/null &
    fi
else
    echo "Usage: ./dot2ps <DOT FILE>" 1>&2
fi

