#!/bin/bash
DIR=$(cd "$( dirname "$0" )" && cd .. && pwd)
REPOS=("exception" "quine-mccluskey" "bn-to-cnf" "bnc" "dlib" "bnmc")
SERVER="git@github.com:gisodal"
if [ $# -gt 0 ]; then
    SERVER=$1
fi

cd $DIR

echo -e "\n==== updating repository wmc ====\n"
git pull

mkdir -p src
cd src

for ((i=0; i < ${#REPOS[@]}; i++)); do
    REPO=${REPOS[$i]}
    if [ -d $REPO ]; then
        echo -e "\n==== updating repository $REPO ====\n"
        cd $REPO
        git pull
        cd ..
    else
        echo -e "\n=== retreiving repository $REPO ====\n"
        git clone $SERVER/${REPO}.git
        echo
    fi
done
echo
echo DONE.

